# gu-st
ipset=/gu-st.ru/block
ipset=/gosuslugi.ru/block
ipset=/mosreg.ru/block
ipset=/nalog.ru/block
ipset=/gov.ru/block

# vk&mail&max
ipset=/userapi.com/block
ipset=/okcdn.ru/block
ipset=/vk.ru/block
ipset=/vk.com/block
ipset=/vkvideo.ru/block
ipset=/vk-portal.net/block
ipset=/tns-counter.ru/block
ipset=/mail.ru/block
ipset=/max.ru/block
ipset=/api.oneme.ru/block
ipset=/oneme.ru/block

# banks
ipset=/sberbank.ru/block
ipset=/sber.ru/block
ipset=/sberdevices.ru/block
ipset=/sbdv.ru/block
ipset=/giga.chat/block
ipset=/vtb.ru/block
ipset=/alfabank.ru/block
ipset=/alfabank.st/block
ipset=/giga.chat/block
ipset=/vtb.ru/block
ipset=/alfabank.ru/block
ipset=/alfabank.st/blockipset=/giga.chat/block
ipset=/vtb.ru/block
ipset=/alfabank.ru/block
ipset=/alfabank.st/block
